[package]
name = "counter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git" }